name: Check Server Status and Notify Slack

on:
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  check-server:
    runs-on: ubuntu-latest

    steps:
      - name: Check ACC official website
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" https://aws-acc.kr)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Server is up"
            echo "status=success" >> $GITHUB_ENV
          else
            echo "Server check failed"
            echo "status=failure" >> $GITHUB_ENV
          fi

      - name: Send message to Slack
        run: |
          if [ "${{ env.status }}" == "success" ]; then
            MSG="ACC 서버가 정상적으로 응답했습니다"
          else
            MSG="ACC 서버 상태에 문제가 감지되었습니다"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MSG\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
